sudo:     required
language: go
go:
  - "1.11"
  - "1.12"
  - "1.13"

env:
  - GO111MODULE=on

before_install: mkdir -p $GOPATH/bin
install:        make install
script:         make test

# TODO: run 'make lint' once it passes
